// JOBS WRITTEN BY AI EXLUDING ID 1

export default [
  {
    title: "Software Engineer",
    company: "AMD",
    description: `Implement and validate GPU-accelerated algorithms for discrete Fourier transforms.
Benchmark, profile and optimize code to maximize throughput on single-GPU, multi-GPU, and clustered systems.
Deliver high-quality code and documentation, following best practices for open-source software development.
Work with key technical experts across AMD and with our partners and customers to improve ROCm applications, libraries, and tools.`,
    type: "Full time",
    salary_range: "142000-214000",
    address: "2500-500 4th Avenue SW Calgary, AB T2P 2V6 Canada",
    latitude: 1,
    longitude: 1,
    requirements:
      "B.Sc. or B.Eng. degree in Computer Science, Software Engineering, Electrical Engineering, Applied Mathematics, or equivalent Advanced degrees, such as M.Sc., M.Eng., Ph.D. are preferred.",
    skills: JSON.stringify("[C, C++, Python, CUDA]"),
  },
  {
    title: "Frontend Developer",
    company: "Calgary Tech Solutions",
    description:
      "Join our team to build responsive web applications using modern JavaScript frameworks.",
    type: "Full-time",
    salary_range: "$75,000 - $95,000",
    address: "707 5th Street SW",
    latitude: 51.0486,
    longitude: -114.0708,
    requirements: "3+ years experience with React",
    skills: JSON.stringify(["React", "JavaScript", "HTML/CSS", "Git"]),
  },
  {
    title: "Data Analyst",
    company: "Suncor Energy",
    description:
      "Analyze large datasets to provide business insights for our energy operations.",
    type: "Full-time",
    salary_range: "$70,000 - $85,000",
    address: "150 6 Ave SW",
    latitude: 51.0452,
    longitude: -114.0673,
    requirements: "Experience with SQL and data visualization tools",
    skills: JSON.stringify(["SQL", "Python", "Tableau", "Excel"]),
  },
  {
    title: "Barista",
    company: "Analog Coffee",
    description: "Craft exceptional coffee drinks in a fast-paced environment.",
    type: "Part-time",
    salary_range: "$16 - $18/hour",
    address: "740 17 Ave SW",
    latitude: 51.038,
    longitude: -114.0752,
    requirements: "Previous coffee shop experience preferred",
    skills: JSON.stringify(["Customer Service", "Latte Art", "Food Safety"]),
  },
  {
    title: "Registered Nurse",
    company: "Foothills Medical Centre",
    description: "Provide patient care in a busy hospital setting.",
    type: "Full-time",
    salary_range: "$80,000 - $95,000",
    address: "1403 29 St NW",
    latitude: 51.0641,
    longitude: -114.1315,
    requirements: "Registered with CARNA, BLS certification",
    skills: JSON.stringify([
      "Patient Care",
      "Medical Documentation",
      "Team Coordination",
    ]),
  },
  {
    title: "Sales Associate",
    company: "CORE Shopping Centre",
    description: "Assist customers and drive sales in our retail location.",
    type: "Part-time",
    salary_range: "$17 - $19/hour",
    address: "324 8 Ave SW",
    latitude: 51.0459,
    longitude: -114.0694,
    requirements: "1+ year retail experience",
    skills: JSON.stringify([
      "Customer Service",
      "Sales",
      "Inventory Management",
    ]),
  },
  {
    title: "DevOps Engineer",
    company: "Benevity",
    description: "Manage cloud infrastructure and implement CI/CD pipelines.",
    type: "Full-time",
    salary_range: "$90,000 - $120,000",
    address: "611 Meredith Rd NE",
    latitude: 51.055,
    longitude: -114.0419,
    requirements: "Experience with AWS and CI/CD tools",
    skills: JSON.stringify(["AWS", "Docker", "Kubernetes", "Terraform"]),
  },
  {
    title: "Restaurant Server",
    company: "OEB Breakfast Co.",
    description: "Provide excellent service in a busy breakfast restaurant.",
    type: "Full-time",
    salary_range: "$15/hour + tips",
    address: "222 5 Ave SW",
    latitude: 51.0507,
    longitude: -114.0665,
    requirements: "Previous serving experience",
    skills: JSON.stringify([
      "Customer Service",
      "POS Systems",
      "Food Knowledge",
    ]),
  },
  {
    title: "Civil Engineer",
    company: "City of Calgary",
    description: "Design and oversee infrastructure projects across the city.",
    type: "Full-time",
    salary_range: "$85,000 - $105,000",
    address: "800 Macleod Trail SE",
    latitude: 51.0461,
    longitude: -114.0565,
    requirements: "Professional Engineering designation, 5+ years experience",
    skills: JSON.stringify([
      "AutoCAD",
      "Project Management",
      "Structural Analysis",
    ]),
  },
  {
    title: "Marketing Coordinator",
    company: "Calgary Stampede",
    description: "Coordinate marketing campaigns for Calgary's iconic event.",
    type: "Contract",
    salary_range: "$60,000 - $70,000",
    address: "1410 Olympic Way SE",
    latitude: 51.0379,
    longitude: -114.052,
    requirements: "Marketing degree and event experience",
    skills: JSON.stringify([
      "Social Media",
      "Event Planning",
      "Graphic Design",
    ]),
  },
  {
    title: "Administrative Assistant",
    company: "Bow Valley College",
    description: "Provide administrative support to department staff.",
    type: "Full-time",
    salary_range: "$45,000 - $55,000",
    address: "345 6 Ave SE",
    latitude: 51.0465,
    longitude: -114.0565,
    requirements: "2+ years office experience",
    skills: JSON.stringify(["MS Office", "Scheduling", "Data Entry"]),
  },
  {
    title: "UX/UI Designer",
    company: "Critical Mass",
    description:
      "Create intuitive user experiences for web and mobile applications.",
    type: "Full-time",
    salary_range: "$75,000 - $95,000",
    address: "833 4 Ave SW",
    latitude: 51.0499,
    longitude: -114.0784,
    requirements: "Portfolio showcasing UX/UI work",
    skills: JSON.stringify([
      "Figma",
      "Adobe XD",
      "User Research",
      "Prototyping",
    ]),
  },
  {
    title: "Pharmacy Technician",
    company: "Shoppers Drug Mart",
    description:
      "Assist pharmacists in filling prescriptions and inventory management.",
    type: "Part-time",
    salary_range: "$22 - $25/hour",
    address: "5149 Country Hills Blvd NW",
    latitude: 51.1546,
    longitude: -114.0714,
    requirements: "Pharmacy Technician certification",
    skills: JSON.stringify([
      "Medication Knowledge",
      "Inventory Management",
      "Customer Service",
    ]),
  },
  {
    title: "Product Manager",
    company: "Shareworks by Morgan Stanley",
    description: "Lead the development of financial software products.",
    type: "Full-time",
    salary_range: "$100,000 - $120,000",
    address: "605 5 Ave SW",
    latitude: 51.048,
    longitude: -114.0743,
    requirements: "5+ years product management experience",
    skills: JSON.stringify([
      "Agile",
      "Financial Knowledge",
      "Roadmapping",
      "User Stories",
    ]),
  },
  {
    title: "Warehouse Associate",
    company: "Amazon",
    description:
      "Pick, pack, and ship customer orders in a fast-paced environment.",
    type: "Full-time",
    salary_range: "$18 - $21/hour",
    address: "5333 61 Ave SE",
    latitude: 51.0006,
    longitude: -113.9546,
    requirements: "Ability to lift 50 lbs consistently",
    skills: JSON.stringify([
      "Inventory Management",
      "Physical Stamina",
      "Attention to Detail",
    ]),
  },
  {
    title: "Elementary School Teacher",
    company: "Calgary Board of Education",
    description: "Teach grade 3 students at a northwest elementary school.",
    type: "Full-time",
    salary_range: "$60,000 - $85,000",
    address: "2908 Morley Trail NW",
    latitude: 51.0887,
    longitude: -114.1348,
    requirements: "Alberta teaching certificate, early education experience",
    skills: JSON.stringify([
      "Curriculum Development",
      "Classroom Management",
      "Student Assessment",
    ]),
  },
  {
    title: "Content Writer",
    company: "Aska Digital",
    description:
      "Create engaging content for websites, blogs, and social media.",
    type: "Contract",
    salary_range: "$30 - $35/hour",
    address: "1331 Macleod Trail SE",
    latitude: 51.0401,
    longitude: -114.0595,
    requirements: "Portfolio of writing samples",
    skills: JSON.stringify([
      "SEO Knowledge",
      "Copywriting",
      "Research",
      "Content Strategy",
    ]),
  },
  {
    title: "Full Stack Developer",
    company: "Neo Financial",
    description: "Build and maintain financial technology applications.",
    type: "Full-time",
    salary_range: "$90,000 - $115,000",
    address: "400 3 Ave SW",
    latitude: 51.0508,
    longitude: -114.07,
    requirements: "Experience with React and Node.js",
    skills: JSON.stringify([
      "JavaScript",
      "React",
      "Node.js",
      "MongoDB",
      "AWS",
    ]),
  },
  {
    title: "Dental Hygienist",
    company: "Deer Valley Dental Care",
    description:
      "Provide dental hygiene services in a friendly clinic environment.",
    type: "Part-time",
    salary_range: "$40 - $45/hour",
    address: "1221 Canyon Meadows Dr SE",
    latitude: 50.9478,
    longitude: -114.0697,
    requirements: "Dental Hygiene certification",
    skills: JSON.stringify([
      "Dental Cleaning",
      "Patient Education",
      "Treatment Planning",
    ]),
  },
  {
    title: "Project Coordinator",
    company: "TransAlta",
    description:
      "Coordinate energy infrastructure projects from planning to completion.",
    type: "Full-time",
    salary_range: "$65,000 - $75,000",
    address: "110 12 Ave SW",
    latitude: 51.0417,
    longitude: -114.0651,
    requirements: "Project management experience in energy sector",
    skills: JSON.stringify([
      "Project Scheduling",
      "Budget Management",
      "Stakeholder Communications",
    ]),
  },
  {
    title: "Sous Chef",
    company: "Model Milk",
    description: "Help lead kitchen operations in an upscale restaurant.",
    type: "Full-time",
    salary_range: "$55,000 - $65,000",
    address: "308 17 Ave SW",
    latitude: 51.038,
    longitude: -114.0714,
    requirements: "5+ years professional cooking experience",
    skills: JSON.stringify([
      "Food Preparation",
      "Menu Development",
      "Kitchen Management",
      "Food Safety",
    ]),
  },
  {
    title: "Financial Analyst",
    company: "ATB Financial",
    description:
      "Analyze financial data and prepare reports for business decisions.",
    type: "Full-time",
    salary_range: "$70,000 - $85,000",
    address: "111 5 Ave SW",
    latitude: 51.0481,
    longitude: -114.0653,
    requirements: "Finance degree and Excel expertise",
    skills: JSON.stringify([
      "Financial Modeling",
      "Excel",
      "Data Analysis",
      "Reporting",
    ]),
  },
  {
    title: "Electrician",
    company: "CANA Construction",
    description:
      "Install and maintain electrical systems in commercial buildings.",
    type: "Full-time",
    salary_range: "$38 - $45/hour",
    address: "7900 11 St SE",
    latitude: 50.9834,
    longitude: -114.035,
    requirements: "Journeyman Electrician certification",
    skills: JSON.stringify([
      "Electrical Installation",
      "Blueprint Reading",
      "Troubleshooting",
      "Safety Protocols",
    ]),
  },
  {
    title: "Customer Service Representative",
    company: "ENMAX",
    description:
      "Handle customer inquiries regarding energy services and billing.",
    type: "Full-time",
    salary_range: "$40,000 - $48,000",
    address: "141 50 Ave SE",
    latitude: 51.0074,
    longitude: -114.061,
    requirements: "Previous customer service experience",
    skills: JSON.stringify([
      "Problem Solving",
      "Communication",
      "Billing Systems",
      "Conflict Resolution",
    ]),
  },
  {
    title: "HR Coordinator",
    company: "WestJet",
    description:
      "Support HR functions including recruitment and employee relations.",
    type: "Full-time",
    salary_range: "$55,000 - $65,000",
    address: "22 Aerial Place NE",
    latitude: 51.1249,
    longitude: -114.0076,
    requirements: "HR education and 2+ years experience",
    skills: JSON.stringify([
      "Recruitment",
      "Employee Relations",
      "HRIS",
      "Policy Implementation",
    ]),
  },
  {
    title: "Graphic Designer",
    company: "Wax Partnership",
    description: "Create visual content for marketing campaigns and branding.",
    type: "Contract",
    salary_range: "$30 - $40/hour",
    address: "809 5 Ave SW",
    latitude: 51.0483,
    longitude: -114.077,
    requirements: "Design portfolio showcasing brand work",
    skills: JSON.stringify([
      "Adobe Creative Suite",
      "Typography",
      "Brand Design",
      "Layout",
    ]),
  },
];
