name: Keep Render Backend Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 15 minutes
  workflow_dispatch:        # Optional manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Add random delay (0–300 seconds)
        run: sleep $((RANDOM % 300))
        
      - name: Simulate real user visit
        run: |
          echo "---- Simulated visit at $(date -u) UTC ----"
          curl -s https://jobcompass-s2az.onrender.com/jobs 
          curl -s https://jobcompass-s2az.onrender.com/jobs/1 > /dev/null

          
